config/routes.rb
Iconsreserve::Application.routes.draw do
  resources :comp_infos

  get "comp_infos/home"

  match 'home' => 'comp_infos#home'
  match 'new' => 'comp_infos#new'
  match 'success' => 'comp_infos#success'

  root :to => 'comp_infos#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/comp_info.rb
class CompInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comp_infos_controller.rb
class CompInfosController < ApplicationController
  # GET /comp_infos
  # GET /comp_infos.json
  def index
    render :layout => "index_layout"
    @comp_infos = CompInfo.all

  end

  def home
     @comp_infos = CompInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comp_infos }
    end
  end

  # GET /comp_infos/1
  # GET /comp_infos/1.json
  def show
    @comp_info = CompInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comp_info }
    end
  end

  # GET /comp_infos/new
  # GET /comp_infos/new.json
  def new
    @comp_info = CompInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comp_info }
    end
  end

  # GET /comp_infos/1/edit
  def edit
    @comp_info = CompInfo.find(params[:id])
  end

  # POST /comp_infos
  # POST /comp_infos.json
  def create
    @comp_info = CompInfo.new(params[:comp_info])

    respond_to do |format|
      if @comp_info.save
        CompMailer.mysubmit(@comp_info).deliver
        format.html { redirect_to :controller => 'comp_infos', :action => 'success' }
        format.json { render json: @comp_info, status: :created, location: @comp_info }
      else
        format.html { render action: "new" }
        format.json { render json: @comp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comp_infos/1
  # PUT /comp_infos/1.json
  def update
    @comp_info = CompInfo.find(params[:id])

    respond_to do |format|
      if @comp_info.update_attributes(params[:comp_info])
        format.html { redirect_to @comp_info, notice: 'Comp info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comp_infos/1
  # DELETE /comp_infos/1.json
  def destroy
    @comp_info = CompInfo.find(params[:id])
    @comp_info.destroy

    respond_to do |format|
      format.html { redirect_to comp_infos_url }
      format.json { head :no_content }
    end
  end

  def submit_res
    @comp_info = CompInfo.new
    #@user = User.find(params[:id])
    #@user = User.where(:id => params[:id])
    #@vipbbsrsbb = Vipbbsrsbb.find(params[:company_email])
    
    CompMailer.mysubmit(@comp_info.comp_name).deliver
    #@email = Vipbbsrsbb.all
    #@comp = Vipbbsrsbb.all
    #UserMailer.send_reserves(@email,@comp).deliver
    redirect_to(:controller => 'comp_info',:action => 'index')
  end

  def success  
    render :layout => "success"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comp_infos_helper.rb
module CompInfosHelper
end

app/views/comp_infos/edit.html.erb
<h1>Editing comp_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @comp_info %> |
<%= link_to 'Back', comp_infos_path %>

app/views/comp_infos/home.html.erb
<h1>List of Registered Company</h1>
<br />
<table>
  <tr>
    <th>Company Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comp_infos.each do |comp_info| %>
  <tr>
    <td><%= link_to comp_info.comp_name , comp_info %></td>
    <td></td>
    <td><%= link_to 'Edit', edit_comp_info_path(comp_info) %></td>
    <td><%= link_to 'Destroy', comp_info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company Reservation', new_comp_info_path %>


<div class="equipment">

  <p>
  <span style="font-size:1.2em;font-weight:bolder;">Technical Equipment (to be provided by PeopleSparx)</span><br /><br />    
  <span style="font-weight:bolder;">STAGE BACKDROP</span> <br />
  Framing of 3 – 9’x12’ LCD Screens 
  <br />  <br />
  <span style="font-weight:bolder;">VIDEO SYSTEM</span><br />
  3 units   9’ x 12’ LCD Screens<br />
  3 units   LCD Rear Projectors<br />
  2 units   Camera System <br />
  1 unit  DVD Harddisk Recording<br />
  2 units   DVD Players<br />
  1 lot                VGA Splitters & Switchers <br />                    
<br /><br />
  <span style="font-weight:bolder;">LIGHTS & SOUND SYSTEM</span><br />
  Audio System<br />
  6 units EAW Type AS690<br />
  4 units RCF 4PRO6001<br />
  6 units EV- Type Sub Scoop, Subwoofer, Powered, 600w<br />
  4    units RCF 4PRO3002SMA, 12” Bi-Amp, Powered Speakers<br />
  2 units Pioneer CDJ 100s CD Players<br />
  1 unit  Stanton SA3, Professional Scratch Mixer (DJ Battle Mixer)<br />
  1   unit 32 channels Digital Mixing Console<br />
  1 lot Shure SM58 Wired Microphone<br />
  4 units Sennheiser eW135 Handheld wireless UHF microphone<br />
<br /><br />
  <span style="font-weight:bolder;">Miscellaneous</span><br />
  1 lot Microphone stands<br />
  1 unit  Whirlwind 32x8x50m Microphone Snake Cable<br />
  4 units Crank-up Mechanical Light Stand. 20’ hoist level<br />
  1 lot Steel Scaffoldings<br />
  1 lot Cables, Connectors & Wiring Materials<br />
  1 unit  Power Distribution Unit, 120 amperes main breaker (3 phase)<br />
  1 unit  Power Distribution Unit, 200 amperes main breaker (3 phase)<br />
  5 units Communication Headsets<br />
<br /><br />
  <span style="font-weight:bolder;">Lighting and Effects</span><br />
  24  units Par 64 lamps <br />
  1 unit  DMX Dimmer Board Light Controller<br />
  16  units Lumilites LED Par 3W<br />
  2 units Jogen 1200 Fog Machine<br />
  2 units Antari HZ100 Haze machine<br />
  2 units Silverstar HMI 1200 Follow Spot<br />
  2 units Jogen Molefay (flash) Audience Blinder Lights<br />
  4 units Pearl River Big Dipper, Profile 575 moving heads<br />
  1 unit  Magic DP1220 DMX 4kva X 12 channel dimmer pack<br />
  1 unit  Avolites Pearl 2010 programmable light mixing console<br />

  </p>
</div>

app/views/comp_infos/index.html.erb
<div>

<div class="logos">
  <%= image_tag('header.png') %>
</div>

<div>
  <div class="img_tag1">
    <div class="one">Register Your Company Online<br /> <a href="http://peoplesparx.net23.net/">Registration Site</a></div>
    <%= image_tag('1.png') %>
  </div>
  <div class="img_tag2">
      <div class="two">Fill Out Your Company Performance Requirements <br /><%= link_to("Fill Up Form", 'new' ) %></div>
    <%= image_tag('2.png') %>
  </div>
  <div class="img_tag3">
      <div class="three">Reserve Seats for the Event<br /> <a href="http://hrcc-icons.herokuapp.com/">Seat Reservation</a></div>
    <%= image_tag('3.png') %>
  </div>
</div>



</div>

app/views/comp_infos/new.html.erb
<h1>Company Performance Requirements</h1>

<%= render 'form' %>

<%= link_to 'Back', comp_infos_path %>

app/views/comp_infos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="field">
    <b>Company Name:</b>
    <%=  @comp_info.comp_name %>
</div>

<div class="field">
    <b>Company Representative:</b>
    <%=  @comp_info.comp_res %>
</div>

<div class="field">
    <b>Company Representative Contact:</b>
    <%=  @comp_info.comp_res_numk %>
</div>

<div class="field">
    <b>Technical Representative:</b>
    <%=  @comp_info.comp_tech_rep %>
</div>

<div class="field">
    <b>Technical Representative: Contact:</b>
    <%=  @comp_info.comp_tech_num %>
</div>
<br />

<h2>Dancers</h2>
<div class="dancer1">
  <div class="field">
     <p>1. <%= @comp_info.dancer1 %></p>
  </div>
 <div class="field">
    <p>2. <%= @comp_info.dancer2 %></p>
  </div>
  <div class="field">
    <p>3. <%= @comp_info.dancer3 %></p>
  </div>
 <div class="field">
    <p>4. <%= @comp_info.dancer4 %></p>
  </div>
  <div class="field">
    <p>5. <%= @comp_info.dancer5 %></p>
  </div>
  <div class="field">
    <p>6. <%= @comp_info.dancer6 %></p>
  </div>
 <div class="field">
    <p>7. <%= @comp_info.dancer7 %></p>
  </div>
  <div class="field">
    <p>8. <%= @comp_info.dancer8 %></p>
  </div>
  <div class="field">
    <p>9. <%= @comp_info.dancer9 %></p>
  </div>
  <div class="field">
    <p>10. <%= @comp_info.dancer10 %></p>
  </div>
   <div class="field">
    <p>11. <%= @comp_info.dancer11 %></p>
  </div>
 <div class="field">
    <p>12. <%= @comp_info.dancer12 %></p>
  </div>
  <div class="field">
    <p>13. <%= @comp_info.dancer13 %></p>
  </div>
</div>

<div class="dancer2">
 <div class="field">
    <p>14. <%= @comp_info.dancer14 %></p>
  </div>
  <div class="field">
    <p>15. <%= @comp_info.dancer15 %></p>
  </div>
  <div class="field">
    <p>16. <%= @comp_info.dancer16 %></p>
  </div>
 <div class="field">
    <p>17. <%= @comp_info.dancer17 %></p>
  </div>
  <div class="field">
    <p>18. <%= @comp_info.dancer18 %></p>
  </div>
  <div class="field">
    <p>19. <%= @comp_info.dancer19 %></p>
  </div>
  <div class="field">
    <p>20. <%= @comp_info.dancer20 %></p>
  </div>
  <div class="field">
    <p>21. <%= @comp_info.dancer21 %></p>
  </div>
  <div class="field">
    <p>22. <%= @comp_info.dancer22 %></p>
  </div>
  <div class="field">
    <p>23. <%= @comp_info.dancer23 %></p>
  </div>
  <div class="field">
    <p>24. <%= @comp_info.dancer24 %></p>
  </div>
  <div class="field">
    <p>25. <%= @comp_info.dancer25 %></p>
  </div>
</div>

<div style="clear:both;padding-top:30px;">
<h2>Number of Microphone</h2>
  <div class="field">
    <%= @comp_info.mics %>
  </div>
</div>
<h2>Props Men</h2>
  <div class="props1">
  <div class="field">
      <p>1. <%= @comp_info.propsmen1 %></p>
  </div>
   <div class="field">
      <p>2. <%= @comp_info.propsmen2 %></p>
  </div>
   <div class="field">
      <p>3. <%= @comp_info.propsmen3 %></p>
  </div>
</div>
  <div class="props2">
   <div class="field">
    <p>4. <%= @comp_info.propsmen4 %></p>
  </div>
   <div class="field">
    <p>5. <%= @comp_info.propsmen5 %></p>
  </div>
   <div class="field">
    <p>6. <%= @comp_info.propsmen6 %></p>
  </div>
</div>


<h2>Personal Assistant</h2>
  <div class="field">
    <%= @comp_info.pa1 %>
  </div>
   <div class="field">
    <%= @comp_info.pa2 %>
  </div>

  <h2>Comments</h2>
  <div class="field">

    <%= @comp_info.comments %>
  </div>


  <h2>Time and Performance Requirement</h2>
  <div class="props1">
   <div class="field">
    <p>1. <%= @comp_info.time1 %></p>
  </div>
  <div class="field">
    <p>2. <%= @comp_info.time2 %></p>
  </div>
  <div class="field">
    <p>3. <%= @comp_info.time3 %></p>
  </div>
  <div class="field">
    <p>4. <%= @comp_info.time4 %></p>
  </div>
  <div class="field">
    <p>5. <%= @comp_info.time5 %></p>
  </div>
  <div class="field">
    <p>6. <%= @comp_info.time6 %></p>
  </div>
  <div class="field">
    <p>7. <%= @comp_info.time7 %></p>
  </div>
  <div class="field">
    <p>8. <%= @comp_info.time8 %></p>
  </div>
   <div class="field">
    <p>9. <%= @comp_info.time9 %></p>
  </div>
  <div class="field">
    <p>10. <%= @comp_info.time10 %></p>
  </div>


  <div class="field">
    <p>11. <%= @comp_info.time11 %></p>
  </div>
  <div class="field">
    <p>12. <%= @comp_info.time12 %></p>
  </div>
  <div class="field">
    <p>13. <%= @comp_info.time13 %></p>
  </div>
  <div class="field">
    <p>14. <%= @comp_info.time14 %></p>
  </div>
  <div class="field">
    <p>15. <%= @comp_info.time15 %></p>
  </div>
  <div class="field">
    <p>16. <%= @comp_info.time16 %></p>
  </div>
  <div class="field">
    <p>17. <%= @comp_info.time17 %></p>
  </div>
  <div class="field">
    <p>18. <%= @comp_info.time18 %></p>
  </div>
   <div class="field">
    <p>19. <%= @comp_info.time19 %></p>
  </div>
  <div class="field">
    <p>20. <%= @comp_info.time20 %></p>
  </div>


  <div class="field">
    <p>21. <%= @comp_info.time21 %></p>
  </div>
  <div class="field">
    <p>22. <%= @comp_info.time22 %></p>
  </div>
  <div class="field">
    <p>23. <%= @comp_info.time23 %></p>
  </div>
  <div class="field">
    <p>24. <%= @comp_info.time24 %></p>
  </div>
  <div class="field">
    <p>25. <%= @comp_info.time25 %></p>
  </div>
  <div class="field">
    <p>26. <%= @comp_info.time26 %></p>
  </div>
  <div class="field">
    <p>27. <%= @comp_info.time27 %></p>
  </div>
  <div class="field">
    <p>28. <%= @comp_info.time28 %></p>
  </div>
   <div class="field">
    <p>29. <%= @comp_info.time29 %></p>
  </div>
  <div class="field">
    <p>30. <%= @comp_info.time30 %></p>
  </div>


<%= link_to 'Edit', edit_comp_info_path(@comp_info) %> |
<%= link_to 'Back', comp_infos_path %>


<div class="equipment">

  <p>
  <span style="font-size:1.2em;font-weight:bolder;">Technical Equipment (to be provided by PeopleSparx)</span><br /><br />    
  <span style="font-weight:bolder;">STAGE BACKDROP</span> <br />
  Framing of 3 – 9’x12’ LCD Screens 
  <br />  <br />
  <span style="font-weight:bolder;">VIDEO SYSTEM</span><br />
  3 units   9’ x 12’ LCD Screens<br />
  3 units   LCD Rear Projectors<br />
  2 units   Camera System <br />
  1 unit  DVD Harddisk Recording<br />
  2 units   DVD Players<br />
  1 lot                VGA Splitters & Switchers <br />                    
<br /><br />
  <span style="font-weight:bolder;">LIGHTS & SOUND SYSTEM</span><br />
  Audio System<br />
  6 units EAW Type AS690<br />
  4 units RCF 4PRO6001<br />
  6 units EV- Type Sub Scoop, Subwoofer, Powered, 600w<br />
  4    units RCF 4PRO3002SMA, 12” Bi-Amp, Powered Speakers<br />
  2 units Pioneer CDJ 100s CD Players<br />
  1 unit  Stanton SA3, Professional Scratch Mixer (DJ Battle Mixer)<br />
  1   unit 32 channels Digital Mixing Console<br />
  1 lot Shure SM58 Wired Microphone<br />
  4 units Sennheiser eW135 Handheld wireless UHF microphone<br />
<br /><br />
  <span style="font-weight:bolder;">Miscellaneous</span><br />
  1 lot Microphone stands<br />
  1 unit  Whirlwind 32x8x50m Microphone Snake Cable<br />
  4 units Crank-up Mechanical Light Stand. 20’ hoist level<br />
  1 lot Steel Scaffoldings<br />
  1 lot Cables, Connectors & Wiring Materials<br />
  1 unit  Power Distribution Unit, 120 amperes main breaker (3 phase)<br />
  1 unit  Power Distribution Unit, 200 amperes main breaker (3 phase)<br />
  5 units Communication Headsets<br />
<br /><br />
  <span style="font-weight:bolder;">Lighting and Effects</span><br />
  24  units Par 64 lamps <br />
  1 unit  DMX Dimmer Board Light Controller<br />
  16  units Lumilites LED Par 3W<br />
  2 units Jogen 1200 Fog Machine<br />
  2 units Antari HZ100 Haze machine<br />
  2 units Silverstar HMI 1200 Follow Spot<br />
  2 units Jogen Molefay (flash) Audience Blinder Lights<br />
  4 units Pearl River Big Dipper, Profile 575 moving heads<br />
  1 unit  Magic DP1220 DMX 4kva X 12 channel dimmer pack<br />
  1 unit  Avolites Pearl 2010 programmable light mixing console<br />

  </p>
</div>

app/views/comp_infos/success.html.erb
<div class="thanks">
	<%= image_tag('thanks.png') %>
</div>
<div class="home">
	<%= link_to(image_tag('home.png'), :controller => 'comp_infos', :action => 'index') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iconsreserve</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
<%= yield %>
	</div>
</body>
</html>

app/views/layouts/index_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iconsreserve</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="crowd">
	<div class="container">
<%= yield %>
	</div>
</body>
</html>

app/views/layouts/success.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iconsreserve</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="crowd">
	<div class="container">
<%= yield %>
	</div>
</body>
</html>